# Generated by Django 3.2 on 2024-06-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bcmr_main', '0027_remove_registry_contents__identities_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bcmr_main.token',),
        ),
    ]
