version: "3.7"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  bchn:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /home/ubuntu/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: "${BCHN_CHIPNET_HOST}"
      LOCAL_PORT: 8332
      REMOTE_PORT: 8332
  zmq:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /home/ubuntu/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: "${BCHN_CHIPNET_HOST}"
      LOCAL_PORT: 28332
      REMOTE_PORT: 28332
  postgres:
    image: "postgres:11.1-alpine"
    volumes:
      - paytaca_bcmr_db_data:/var/lib/postgresql/data
    env_file:
      - /home/ubuntu/paytaca-bcmr/compose/.env_chipnet
    expose:
      - "5432"
  redis:
    image: "redis:alpine"
    env_file:
      - /home/ubuntu/paytaca-bcmr/compose/.env_chipnet
  backend:
    container_name: paytaca_bcmr_backend
    build: /home/ubuntu/paytaca-bcmr
    image: paytaca_bcmr_web
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    env_file: /home/ubuntu/paytaca-bcmr/compose/.env_chipnet
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
volumes:
  paytaca_bcmr_db_data:
    external: true
