version: "3.7"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  postgres:
    image: "postgres:11.1-alpine"
    volumes:
      - paytaca_bcmr_db_data:/var/lib/postgresql/data
    env_file:
      - /root/paytaca-bcmr/compose/.env_mainnet
    expose:
      - "5432"
  redis:
    image: "redis:alpine"
    env_file:
      - /root/paytaca-bcmr/compose/.env_mainnet
  backend:
    container_name: paytaca_bcmr_backend
    build: /root/paytaca-bcmr
    image: paytaca_bcmr_web
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    env_file: /root/paytaca-bcmr/compose/.env_mainnet
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
volumes:
  paytaca_bcmr_db_data:
    external: true
