# Generated by Django 3.1.6 on 2023-06-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
