# Generated by Django 3.1.6 on 2023-05-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.JSONField(default=dict)),
                ('registry_identity', models.JSONField(default=dict)),
                ('latest_revision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Registries',
                'ordering': ('-latest_revision',),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('category', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('decimals', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('is_nft', models.BooleanField(default=False)),
                ('nfts', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('burned', 'Burned')], default='active', max_length=10)),
            ],
            options={
                'ordering': ('name', 'symbol', 'is_nft'),
            },
        ),
        migrations.DeleteModel(
            name='FungibleToken',
        ),
        migrations.AddField(
            model_name='registry',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registry', to='bcmr_main.token'),
        ),
    ]
