# Generated by Django 3.1.6 on 2023-06-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('date_acquired', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date_acquired',),
            },
        ),
        migrations.AddIndex(
            model_name='identityoutput',
            index=models.Index(fields=['txid', 'category', 'spent'], name='bcmr_main_i_txid_c12f74_idx'),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['category'], name='bcmr_main_r_categor_78d832_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['category', 'commitment', 'capability', 'is_nft'], name='bcmr_main_t_categor_980116_idx'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='bcmr_main.token'),
        ),
        migrations.AddIndex(
            model_name='ownership',
            index=models.Index(fields=['address'], name='bcmr_main_o_address_45c3dc_idx'),
        ),
    ]
