# Generated by Django 3.1.6 on 2023-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0002_registry_validity_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityoutput',
            name='identities',
            field=models.ManyToManyField(null=True, related_name='_identityoutput_identities_+', to='bcmr_main.IdentityOutput'),
        ),
    ]
