# Generated by Django 3.1.6 on 2023-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0002_auto_20230514_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='token',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
