# Generated by Django 3.1.6 on 2023-06-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0002_auto_20230611_2356'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ownership',
            name='bcmr_main_o_address_45c3dc_idx',
        ),
        migrations.RemoveField(
            model_name='token',
            name='bcmr_url',
        ),
        migrations.AddField(
            model_name='ownership',
            name='burned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownership',
            name='burner',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='spender',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='spent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='category',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='parent_txid',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='txid',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='txid',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='category',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='registry',
            name='txid',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='category',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='token',
            name='txid',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddIndex(
            model_name='ownership',
            index=models.Index(fields=['address', 'spent', 'burned'], name='bcmr_main_o_address_a7530f_idx'),
        ),
    ]
