# Generated by Django 3.1.6 on 2023-06-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0003_auto_20230612_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='token',
            old_name='updated_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='txid',
            new_name='debut_txid',
        ),
        migrations.AddField(
            model_name='ownership',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
