# Generated by Django 3.1.6 on 2023-05-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0004_identityoutput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityoutput',
            options={'ordering': ('-block',)},
        ),
        migrations.AddField(
            model_name='identityoutput',
            name='block',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
