# Generated by Django 3.1.6 on 2023-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0004_auto_20230612_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityoutput',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Identity Outputs'},
        ),
        migrations.RemoveIndex(
            model_name='identityoutput',
            name='bcmr_main_i_txid_c12f74_idx',
        ),
        migrations.RemoveField(
            model_name='identityoutput',
            name='category',
        ),
        migrations.AddField(
            model_name='registry',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='identityoutput',
            index=models.Index(fields=['txid', 'parent_txid', 'spent'], name='bcmr_main_i_txid_3d35ba_idx'),
        ),
    ]
