# Generated by Django 3.1.6 on 2023-06-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0005_token_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenmetadata',
            options={'verbose_name_plural': 'Token metadata'},
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
