# Generated by Django 3.1.6 on 2023-05-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0005_auto_20230522_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityoutput',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_outputs', to='bcmr_main.token'),
        ),
    ]
