# Generated by Django 3.1.6 on 2023-06-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0005_auto_20230612_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registries', to='bcmr_main.identityoutput'),
        ),
    ]
