# Generated by Django 3.1.6 on 2023-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0006_registry_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityoutput',
            name='parent_txid',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
