# Generated by Django 3.1.6 on 2023-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0006_auto_20230614_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=70, unique=True)),
                ('details', models.JSONField()),
            ],
        ),
    ]
