# Generated by Django 3.1.6 on 2023-06-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0006_auto_20230614_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='txid',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('txid', 'token')},
        ),
    ]
