# Generated by Django 3.1.6 on 2023-05-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0006_auto_20230522_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentityOutput',
        ),
    ]
