# Generated by Django 3.1.6 on 2023-06-14 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0006_auto_20230614_0130'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='identityoutput',
            name='bcmr_main_i_txid_1a4f55_idx',
        ),
        migrations.RemoveField(
            model_name='identityoutput',
            name='identities',
        ),
        migrations.AddField(
            model_name='identityoutput',
            name='identities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='identityoutput',
            index=models.Index(fields=['txid', 'spent', 'authbase'], name='bcmr_main_i_txid_e88a5f_idx'),
        ),
    ]
