# Generated by Django 3.1.6 on 2023-06-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0007_auto_20230612_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveIndex(
            model_name='registry',
            name='bcmr_main_r_categor_78d832_idx',
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['category', 'valid'], name='bcmr_main_r_categor_acf2a4_idx'),
        ),
    ]
