# Generated by Django 3.1.6 on 2023-06-15 06:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0007_queuedtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedtransaction',
            name='details',
            field=models.JSONField(decoder=django.core.serializers.json.DjangoJSONEncoder, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
