# Generated by Django 3.1.6 on 2023-06-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0007_auto_20230614_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('txid', 'index')},
        ),
    ]
