# Generated by Django 3.1.6 on 2023-05-24 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0007_delete_identityoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField()),
                ('block', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_identity_output', models.BooleanField(default=False)),
                ('authbase', models.BooleanField(default=False)),
                ('genesis', models.BooleanField(default=False)),
                ('spent', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='bcmr_main.token')),
            ],
            options={
                'ordering': ('-date_created',),
                'unique_together': {('txid', 'index')},
            },
        ),
    ]
