# Generated by Django 3.1.6 on 2023-06-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0008_auto_20230615_0627'),
        ('bcmr_main', '0007_auto_20230614_1538'),
    ]

    operations = [
    ]
