# Generated by Django 3.1.6 on 2023-06-16 07:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0008_auto_20230615_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='token_input_identities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
