# Generated by Django 3.1.6 on 2023-06-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0008_auto_20230613_0009'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='identityoutput',
            name='bcmr_main_i_txid_3d35ba_idx',
        ),
        migrations.RemoveField(
            model_name='identityoutput',
            name='parent_txid',
        ),
        migrations.AddIndex(
            model_name='identityoutput',
            index=models.Index(fields=['txid', 'spent'], name='bcmr_main_i_txid_1a4f55_idx'),
        ),
    ]
