# Generated by Django 3.1.6 on 2023-06-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0009_auto_20230613_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=1)),
                ('transactions', models.IntegerField(default=0)),
                ('scan_started', models.DateTimeField(null=True)),
                ('scan_completed', models.DateTimeField(null=True)),
                ('scanned', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
