# Generated by Django 3.1.6 on 2023-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0009_merge_20230615_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenmetadata',
            options={'get_latest_by': 'date_created', 'verbose_name_plural': 'Token metadata'},
        ),
        migrations.RemoveIndex(
            model_name='registry',
            name='bcmr_main_r_txid_ccbdd5_idx',
        ),
        migrations.AlterField(
            model_name='queuedtransaction',
            name='details',
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['txid', 'index', 'valid', 'date_created'], name='bcmr_main_r_txid_426edd_idx'),
        ),
    ]
