# Generated by Django 3.1.6 on 2023-05-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0009_auto_20230524_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='bcmr_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='bcmr_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
