# Generated by Django 3.1.6 on 2023-05-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0010_auto_20230525_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='token',
        ),
        migrations.DeleteModel(
            name='IdentityOutput',
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
