# Generated by Django 3.1.6 on 2023-05-25 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bcmr_main', '0011_auto_20230525_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('category', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('url', models.URLField(max_length=255)),
                ('latest_revision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Registries',
                'ordering': ('-latest_revision',),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('is_nft', models.BooleanField(default=False)),
                ('commitment', models.CharField(blank=True, max_length=255, null=True)),
                ('capability', models.CharField(blank=True, choices=[('minting', 'Minting'), ('mutable', 'Mutable'), ('none', 'None')], max_length=20, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='bcmr_main.registry')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('category', 'commitment')},
            },
        ),
        migrations.CreateModel(
            name='IdentityOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField()),
                ('block', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('authbase', models.BooleanField(default=False)),
                ('genesis', models.BooleanField(default=False)),
                ('spent', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='bcmr_main.token')),
            ],
            options={
                'ordering': ('-date_created',),
                'unique_together': {('txid', 'index')},
            },
        ),
    ]
