# Generated by Django 3.1.6 on 2023-06-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0011_token_category_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='category_metadata',
        ),
        migrations.AddField(
            model_name='tokenmetadata',
            name='metadata_type',
            field=models.CharField(blank=True, choices=[('category', 'Category'), ('type', 'Type')], max_length=20, null=True),
        ),
    ]
