# Generated by Django 3.1.6 on 2023-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0012_auto_20230617_0247'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tokenmetadata',
            index=models.Index(fields=['metadata_type', 'date_created'], name='bcmr_main_t_metadat_8d3871_idx'),
        ),
    ]
