# Generated by Django 3.1.6 on 2023-05-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0012_identityoutput_registry_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
