# Generated by Django 3.1.6 on 2023-05-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0014_auto_20230525_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityoutput',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'Identity Outputs'},
        ),
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name_plural': 'Registries'},
        ),
        migrations.RenameField(
            model_name='registry',
            old_name='data',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='latest_revision',
        ),
    ]
