# Generated by Django 3.1.6 on 2023-05-31 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0015_auto_20230526_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='registry',
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
