# Generated by Django 3.2 on 2023-06-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0015_auto_20230620_0528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tokenmetadata',
            unique_together={('token', 'identity', 'registry', 'metadata_type')},
        ),
    ]
