# Generated by Django 3.1.6 on 2023-05-31 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0016_auto_20230531_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid', models.BooleanField(default=False)),
                ('op_return', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Registries',
                'ordering': ('-date_created',),
            },
        ),
    ]
