# Generated by Django 3.2 on 2023-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0016_alter_tokenmetadata_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registry',
            name='bcmr_main_r_txid_426edd_idx',
        ),
        migrations.AddField(
            model_name='registry',
            name='generated_metadata',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(fields=['txid', 'index', 'valid', 'date_created', 'generated_metadata'], name='bcmr_main_r_txid_49f468_idx'),
        ),
    ]
