# Generated by Django 3.2 on 2023-07-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0017_auto_20230621_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityoutput',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='txid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='burner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='spender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='txid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='queuedtransaction',
            name='txid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='txid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='debut_txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
