# Generated by Django 3.1.6 on 2023-05-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0017_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='op_return',
            field=models.TextField(default=''),
        ),
    ]
