# Generated by Django 3.2 on 2023-07-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0007_auto_20230614_0912'),
        ('bcmr_main', '0017_auto_20230621_1456'),
    ]

    operations = [
    ]
