# Generated by Django 3.2 on 2023-07-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0009_ownership_token_input_identities'),
        ('bcmr_main', '0018_merge_0007_auto_20230614_0912_0017_auto_20230621_1456'),
    ]

    operations = [
    ]
