# Generated by Django 3.2 on 2023-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0018_auto_20230723_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityoutput',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='burner',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='spender',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
