# Generated by Django 3.1.6 on 2023-06-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0018_auto_20230531_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='txid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
