# Generated by Django 3.1.6 on 2023-06-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0019_registry_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='bcmr_request_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='bcmr_url',
            field=models.TextField(default=''),
        ),
    ]
