# Generated by Django 3.2 on 2023-10-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0019_auto_20230723_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='allow_hash_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
