# Generated by Django 3.2 on 2023-07-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0019_auto_20230723_1512'),
        ('bcmr_main', '0019_merge_20230723_0233'),
    ]

    operations = [
    ]
