# Generated by Django 3.2 on 2023-07-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0019_auto_20230723_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='burner',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='spender',
        ),
        migrations.AddField(
            model_name='ownership',
            name='amount',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='burner_txid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='spender_txid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
