# Generated by Django 3.2 on 2023-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0020_auto_20230726_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='burner_txid',
        ),
    ]
