# Generated by Django 3.1.6 on 2023-06-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0020_auto_20230605_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='txid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
