# Generated by Django 3.1.6 on 2023-06-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0021_auto_20230606_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityoutput',
            name='authhead',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='identityoutput',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identityoutput',
            name='spent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bcmr_main.identityoutput'),
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='txid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='identityoutput',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='identityoutput',
            name='index',
        ),
        migrations.RemoveField(
            model_name='identityoutput',
            name='token',
        ),
    ]
