# Generated by Django 3.2 on 2023-10-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0021_registry_watch_for_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
