# Generated by Django 3.2 on 2023-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0021_remove_ownership_burner_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='txid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('txid', 'index')},
        ),
    ]
