# Generated by Django 3.2 on 2023-10-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0022_registry_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='content',
        ),
    ]
