# Generated by Django 3.2 on 2023-07-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0023_alter_ownership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='acquired_by',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('minting', 'Minting'), ('mutation', 'Mutation')], db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
