# Generated by Django 3.1.6 on 2023-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0023_remove_identityoutput_authhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityoutput',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
