# Generated by Django 3.2 on 2023-07-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0024_ownership_acquired_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='acquired_by',
            new_name='acquired_via',
        ),
    ]
