# Generated by Django 3.1.6 on 2023-06-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0024_auto_20230608_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityoutput',
            name='category',
        ),
    ]
