# Generated by Django 3.2 on 2024-02-22 14:46

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0024_auto_20240125_0058'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registry',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('contents'), name='contents_idx'),
        ),
    ]
