# Generated by Django 3.2 on 2024-02-22 15:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0025_registry_contents_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registry',
            index=models.Index(django.db.models.expressions.F('contents__identities'), name='contents__identities_idx'),
        ),
    ]
