# Generated by Django 3.1.6 on 2023-06-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0026_identityoutput_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentityOutput',
        ),
    ]
