# Generated by Django 3.2 on 2024-06-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0026_registry_contents__identities_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registry',
            name='contents__identities_idx',
        ),
    ]
