# Generated by Django 3.1.6 on 2023-06-08 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0027_delete_identityoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('block', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(default='', max_length=255)),
                ('authbase', models.BooleanField(default=False)),
                ('genesis', models.BooleanField(default=False)),
                ('spent', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('spent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bcmr_main.identityoutput')),
            ],
            options={
                'verbose_name_plural': 'Identity Outputs',
                'ordering': ('-date_created',),
            },
        ),
    ]
