# Generated by Django 3.1.6 on 2023-06-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0028_identityoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityoutput',
            name='txid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
