# Generated by Django 3.1.6 on 2023-06-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0029_auto_20230608_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityoutput',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='identityoutput',
            name='txid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
