# Generated by Django 3.1.6 on 2023-06-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr_main', '0030_auto_20230608_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityoutput',
            options={'verbose_name_plural': 'Identity Outputs'},
        ),
        migrations.RenameField(
            model_name='identityoutput',
            old_name='spent_by',
            new_name='spender',
        ),
        migrations.RemoveField(
            model_name='identityoutput',
            name='date_created',
        ),
    ]
